import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:just_audio/just_audio.dart';

class HapticAudioPipe {
  static const MethodChannel _channel = MethodChannel('com.haptics.audio_pipe');
  final AudioPlayer _player;

  HapticAudioPipe(this._player) {
    // Listen for the session ID to be generated by ExoPlayer
    _player.androidAudioSessionIdStream.listen((sessionId) async {
      if (sessionId != null) {
        await _attachHaptics(sessionId);
      }
    });
  }

  Future<void> _attachHaptics(int sessionId) async {
    try {
      await _channel.invokeMethod('attachHaptics', {'sessionId': sessionId});
      debugPrint('Haptics attached to session: $sessionId');
    } catch (e) {
      debugPrint("Failed to attach haptics: $e");
    }
  }

  Future<void> dispose() async {
    await _channel.invokeMethod('release');
  }
}